config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :courses
    resources :grades
    
    root to: "users#index"
  end

  resources :users
  resources :courses do
    resources :grades, only: [:create, :update, :destroy]
    resources :student_courses, only: [:create, :destroy] 
  end

  resources :grades

  root to: 'users#new'

  get "up" => "rails/health#show", as: :rails_health_check

  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"

  match "*path", to: "application#not_found", via: :all


end

app/controllers/admin/courses_controller.rb
module Admin
  class CoursesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :require_teacher, only: [:new, :create]
  before_action :authenticate_user!, only: [:show]

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @student_course = StudentCourse.find_by(
    student: current_user.id,
    course: @course
    )
    @grade = @student_course&.grades
    @students = @course.students
  end

  def new
    @course = Course.new
  end

  def create 
    @name = params[:course][:name]
    @code = params[:course][:code]

    @new_course = Course.new(name: @name, code: @code, teacher: current_user)
    if @new_course.save
      redirect_to course_path(@new_course)
    else
      render :new
    end
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course_card.html.erb
<div class="border p-4 rounded shadow hover:shadow-lg transition">
  <h2 class="text-xl font-semibold"><%= course.name %></h2>
  <p class="text-gray-600"><%= course.code %></p>
  <p class="mt-2 text-sm text-gray-500">
    Nauczyciel:
    <%= course.teacher&.first_name %> <%= course.teacher&.last_name %>
  </p>

  <%= link_to "Szczegóły",
      course_path(course),
      class: "mt-3 inline-block text-blue-500 hover:underline" %>
</div>

app/views/courses/_student_table.html.erb
<div class="overflow-x-auto  ">
    <table class="sm:w-full  border border-gray-300 rounded" >
        <thead class="bg-gray-100">
            <tr>
                <th class="border p-2 text-left">
                    <div class="flex justify-between">
                            Ocena
                        <button 
                            data-action="click->sort#sort"
                            data-direction="value"
                            > 
                            ↑↓
                        </button>
                    </div>
                </th>
                <th class="border p-2 text-left">
                    <div class="flex justify-between">

                    Opis oceny
                    <button 
                        data-action="click->sort#sort"
                        data-direction="grade_desc"
                        > 
                        ↑↓
                    </button>
                    </div>
                </th>
                <th class="border p-2 text-left">
                    <div class="flex justify-between">
                        Data dodania
                        <button 
                            data-action="click->sort#sort"
                            data-direction="created_at"
                            > 
                            ↑↓
                        </button>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody data-sort-target="tbody">
            <% @grade.each do |grade| %>
                <tr class="border-b" data-sort-row data-value="<%= grade.value %>" data-grade_desc="<%= grade.grade_desc %>" data-created_at="<%= grade.created_at.to_i %>">
                <td class="border p-2">
                    <h1 class="text-center text-2xl font-bold"><%= grade.value %></h1>
                </td>  
                <td class="border p-2"><%= grade.grade_desc %></td>
                <td class="border p-2">
                    <p><%= grade.created_at.strftime("%Y-%m-%d %H:%M") %></p>
                </td>   
                <tr> 
            <% end %>
        </tbody>
    </table>
</div>

app/views/courses/_teacher_table.html.erb
 <div class="overflow-x-auto  ">
    <table class=" sm:w-full border border-gray-300 rounded">
        <thead class="bg-gray-100">
            <tr>
                <th class="border p-2 text-left">
                    <div class="flex justify-between">
                        Student
                        <button 
                            data-action="click->sort#sort"
                            data-direction="name"
                            > 
                            ↑↓
                        </button>
                    </div>
                </th>
                <th class="border p-2 text-left">
                        <div class="flex justify-between">
                        oceny
                    </div>
                </th>
                <th class="border p-2 text-left">Dodaj</th>
            </tr>
        </thead>
        <tbody data-sort-target="tbody">
            <% @students.each do |studentDetails| %>
                <tr class="border-b"
                    data-sort-row
                    data-name="<%= studentDetails.first_name %> <%= studentDetails.last_name %>"
                    >
                    <td class="border p-2"><%= studentDetails.first_name %> <%= studentDetails.last_name %></td>
                    <td class="border p-2"> 
                        <% studentDetails.grades.each do |grade| %>
                            <div data-grade-target="grade" data-url="<%= grade_path(grade) %>" class="flex items-center gap-2 mb-1">
                                <span class="px-2 py-1 border rounded"><%= grade.value %></span>
                                <span> <%= grade&.grade_desc %> </span>
                                <p><%= grade.created_at.strftime("%Y-%m-%d %H:%M") %></p>

                                <button data-action="click->grade#open" class="bg-blue-500 text-white px-2 py-1 rounded">Zmień</button>

                                <button data-action="click->grade#remove" class="bg-red-500 text-white px-2 py-1 rounded">Usuń</button>

                                <div data-grade-target="form" class="hidden fixed inset-0 flex items-center justify-center z-50">
                                    <div class="absolute inset-0 bg-gray-500 bg-opacity-30 backdrop-blur-sm"></div>

                                    <%= form_with url: course_grade_path(@course, grade), method: :patch,
                                            class:"relative z-20 bg-white p-6 rounded shadow-lg flex flex-col gap-4 w-80", local: true do |f| %>
                                        <%= hidden_field_tag :student_id, studentDetails.id %>
                                        <%= hidden_field_tag :grade_id, grade.id %>
                                        <%= number_field_tag :grade, grade.value, in: 2.0..5.0, class: "border p-1 rounded" %>
                                        <%= text_field_tag :grade_desc, grade.grade_desc , class: "border p-1 rounded" %>     
                                        <div class="flex justify-between">
                                            <%= f.submit "Zapisz", class: "bg-green-500 text-white px-4 py-2 rounded cursor-pointer" %>
                                            <button type="button" class="bg-red-500 text-white px-4 py-2 rounded" data-action="click->grade#close">Zamknij</button>
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                        <% end %>
                    </td>
                    <td class="border p-2 ">
                        <button data-action="click->grade#newGradeOpen" class="bg-blue-500 text-white px-2 py-1 rounded">Dodaj</button>
                        <div data-grade-target="newForm" class="hidden fixed inset-0 flex items-center justify-center z-50">
                            <div class="absolute inset-0 bg-gray-500 bg-opacity-30 backdrop-blur-sm"></div>
                            <%= form_with model: Grade.new, url: course_grades_path(@course),
                                class:"relative z-20 bg-white p-6 rounded shadow-lg flex flex-col gap-4 w-80", local: true do |f| %>
                                        <%= hidden_field_tag :student_id, studentDetails.id %>
                                        <%= f.number_field :value, value: 2, in: 2.0..5.0, step: 0.5, class: "border p-1 rounded" %>     
                                        <%= f.text_field :grade_desc, class: "border p-1 rounded", value: "", placeholder: "Opis oceny" %>     
                                        <div class="flex justify-between">
                                            <%= f.submit "Dodaj", class: "bg-green-500 text-white px-4 py-2 rounded cursor-pointer" %>
                                            <button type="button" class="bg-red-500 text-white px-4 py-2 rounded" data-action="click->grade#newGradeClose">Zamknij</button>
                                        </div>
                            <% end %>
                        </div>

                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
 </div>

app/views/courses/index.html.erb
<div class="flex flex-col m-auto w-9/12">
    <div class="flex flex-col-reverse sm:flex-row justify-between mb-4">
        <h1 class="text-2xl mb-4">Wszystkie kursy</h1>
        <% if ["admin", "teacher"].include?(current_user&.role) %> 
            <%= link_to "Dodaj nowy Kurs +", new_course_path, class: "hover:underline text-2xl py-3 sm:py-0 font-bold mb-4" %> 
        <% end %>
    </div>
    <div data-controller="course-search">
        <input
            data-course-search-target="input"
            data-action="input->course-search#search"
            type="text"
            placeholder="Szukaj kursów..."
            class="w-full border p-2 rounded mb-4"
        >
        <div class="flex">
            <select
                data-course-search-target="sort"
                data-action="change->course-search#sort"
                class="border p-2 rounded mb-4"
            >
                <option value="name_asc">Nazwa A–Z</option>
                <option value="name_desc">Nazwa Z–A</option>
                <option value="code_asc">Kod A–Z</option>
                <option value="code_desc">Kod Z–A</option>
            </select>
        </div>
        
          <div data-course-search-target="list" class="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <% @courses.each do |course| %>
                <div
                    data-course-search-target="card"
                    data-name="<%= course.name.downcase %>"
                    data-code="<%= course.code.downcase %>"
                >
                    <%= render "courses/course_card", course: course %>
                </div>
            <% end %>
            </div>


    </div>
</div>

app/views/courses/new.html.erb
<div class="w-9/12 flex m-auto justify-between"
     data-controller="course-preview" >
    <div style="min-width: 300px">
        <h1 class="text-2xl font-bold mb-4">Podgląd</h1>
        <div class="border p-4 rounded shadow hover:shadow-lg transition w-">
            <h2 class="text-xl font-semibold"
                data-course-preview-target="previewName"><%= @course.name || "Name" %></h2>
            <p class="text-gray-600"
                data-course-preview-target="previewCode"><%= @course.code || "C123" %></p>
            <p class="mt-2 text-sm text-gray-500">
                Nauczyciel:
                <%= current_user&.first_name %> <%= current_user&.last_name %>
            </p>
        </div>


    </div>

    <div>
        <h1 class="text-2xl font-bold mb-4" >Dodaj</h1>
            
         <%= form_with model: @course, local: true , class: "flex flex-col gap-3 justify-center align-center rounded border p-4" do |f| %>
            <div class="flex gap-3">
                <%= f.label :name %>
                <%= f.text_field :name , class: "border p-2 rounded" ,  data: { action: "input->course-preview#preview",
                        course_preview_target: "name" }%>
            </div>

            <div class="flex gap-3">
                <%= f.label :code %>
                <%= f.text_field :code, 
                    pattern: "[A-Z]{3}[0-9]{3}",
                    title: "np: ABC123",
                    class: "border p-2 rounded",  
                    data: { action: "input->course-preview#preview",
                            course_preview_target: "code" } %>
            </div>

            <%= f.submit "Utwórz kurs", class: "underline" %>
            <% end %>
            
        </div>


</div>

app/views/courses/show.html.erb
<div class="flex flex-col justify-center" data-controller="grade sort course" >
    <h1 class="mb-4 text-center text-3xl sm:text-6xl font-bold"><%= @course.name %></h1>
    <div class="mt-4">
       <div>
        <% if current_user == @course.teacher %>
           <%= render "teacher_table", students: @students, course: @course %>
        <% else %>
            <% if @grade.present? %>
                <%= render "student_table", grade: @grade%>
            <% elsif @student_course.nil? %>
                <h1 data-course-target="sign_up" data-url="<%= course_student_courses_path(@course) %>" data-action="click->course#sign" class=" cursor-pointer hover:underline mb-4 text-center text-2xl font-bold">Zapisz się</h1>
            <% else %>
                <h1 class="mb-4 text-center text-3xl sm:text-6xl font-bold">Brak ocen</h1>
            <% end %>
        <% end %>
        </div>
    </div>
</div>