config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :courses
    resources :grades
    
    root to: "users#index"
  end

  resources :users
  resources :courses do
    resources :grades, only: [:create, :update, :destroy]
    resources :student_courses, only: [:create, :destroy] 
  end

  resources :grades

  root to: 'users#new'

  get "up" => "rails/health#show", as: :rails_health_check

  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"

  match "*path", to: "application#not_found", via: :all


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Uczelnia" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen flex flex-col">
      <header class=" bg-blue-600 text-white p-4 shadow-md">
      <div class="container mx-auto flex flex-col sm:flex-row justify-between items-center">
          <%= link_to "Uczelnia", root_path, class: "sm:px-2 text-3xl font-bold" %>
        <nav class="flex gap-3">
            <%= link_to "Kursy", courses_path, class: "sm:px-2 hover:underline" %>
          <% if current_user %>
           <% if current_user.role == 'admin' %>
            <%= link_to "Admin Panel", admin_root_path, class: "sm:px-2 hover:underline" %>
           <% end %>
            <%= link_to current_user.first_name, user_path(current_user), class: "sm:px-2 hover:underline" %>
            <%= button_to "Logout", logout_path, method: :delete, class: "sm:px-2 hover:underline" %>
          <% else %>
            <%= link_to "Login", login_path, class: "sm:px-2 hover:underline" %>
          <% end %>
        </nav>

      </div>
    </header>
    <div class="container mx-auto mt-7 flex-1">
      <%= yield %>
    </div>
    <footer class="mt-5 border-t w-10/12 mx-auto">
      <p class="p-4 text-center text-gray-400">Created by: Kajetan Jankowski</p>
    </footer>
  </body>
</html>